site_name: Instant Auto
site_description: Text-based autonomous programming framework for FTC

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Actions: actions.md


plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition